spring:
  application:
    name: employee-gateway

eureka:
  client:
    service-url:
      defaultZone: https://employee-registry-3yo1.onrender.com/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: salary-service
          uri: lb://salary-service
          predicates:
            - Path=/salary/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
