spring:
  application:
    name: employee-gateway

eureka:
  client:
    # Use kebab-case so Spring Boot binding is crystal-clear
    service-url:
      default-zone: https://employee-registry-3yo1.onrender.com/eureka/
    # Optional retries to handle startup-order race:
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: salary-service
          uri: lb://salary-service
          predicates:
            - Path=/salary/**
